using ClosedXML.Excel;
using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
using Produktionsplanung.App.Models;

namespace Produktionsplanung.App.Services;

public sealed record MasterDataImportResult(string Area, int NewCount, int UpdatedCount, IReadOnlyList<string> Errors)
{
    public string Summary => $"{Area}: {NewCount} neu, {UpdatedCount} aktualisiert" + (Errors.Count == 0 ? "." : $", {Errors.Count} Fehler.");
}
public static class MasterDataExcelImportService
{
    public static void CreateTemplate(string path)
    {
        using var wb=new XLWorkbook();
        var e=wb.Worksheets.Add("Mitarbeitende"); Header(e,"Personalnummer","Vorname","Nachname","Funktion","Abteilung","PensumProzent","SollstundenWoche","Aktiv","Qualifikationen");
        e.Cell(2,1).Value="P001";e.Cell(2,2).Value="Max";e.Cell(2,3).Value="Muster";e.Cell(2,4).Value="Operator";e.Cell(2,5).Value="Produktion";e.Cell(2,6).Value=100;e.Cell(2,7).Value=40;e.Cell(2,8).Value="Ja";e.Cell(2,9).Value="Abfüllung:2;Reinigung:3"; e.Column(1).Style.NumberFormat.Format="@";
        var w=wb.Worksheets.Add("Arbeitsplätze"); Header(w,"Name","Bereich","Minimum","Optimal","Maximum","Aktiv","Pflichtqualifikation","SkillLevel"); w.Cell(2,1).Value="Linie 1";w.Cell(2,2).Value="Produktion";w.Cell(2,3).Value=1;w.Cell(2,4).Value=2;w.Cell(2,5).Value=3;w.Cell(2,6).Value="Ja";
        var s=wb.Worksheets.Add("Schichten"); Header(s,"Name","Start","Ende","PauseMinuten");s.Cell(2,1).Value="Früh";s.Cell(2,2).Value="06:00";s.Cell(2,3).Value="14:00";s.Cell(2,4).Value=30;
        var o=wb.Worksheets.Add("Produktionsaufträge"); Header(o,"Auftragsnummer","Artikelnummer","Chargennummer","Menge","Datum","Arbeitsplatz","Schicht","AnzahlSchichten","Personalbedarf","Priorität","Kommentar"); o.Cell(2,1).Value="AUF-001";o.Cell(2,2).Value="0001";o.Cell(2,3).Value="CH-001";o.Cell(2,4).Value=1000;o.Cell(2,5).Value=DateTime.Today;o.Cell(2,6).Value="Linie 1";o.Cell(2,7).Value="Früh";o.Cell(2,8).Value=1;o.Cell(2,9).Value=2;o.Cell(2,10).Value="Normal";
        foreach(var ws in wb.Worksheets){ws.SheetView.FreezeRows(1);ws.Columns().AdjustToContents();} wb.SaveAs(path);
    }
    public static IReadOnlyList<MasterDataImportResult> Import(string path,bool dryRun)
    {
        BatchService.RequirePlanner(); using var wb=new XLWorkbook(path); var results=new List<MasterDataImportResult>();
        using var db=new AppDbContext(); using var tx=db.Database.BeginTransaction();
        if(wb.TryGetWorksheet("Mitarbeitende",out var e)) results.Add(Employees(db,e));
        if(wb.TryGetWorksheet("Arbeitsplätze",out var w)) results.Add(Workstations(db,w));
        if(wb.TryGetWorksheet("Schichten",out var s)) results.Add(Shifts(db,s));
        if(wb.TryGetWorksheet("Produktionsaufträge",out var o)) results.Add(Orders(db,o));
        if(dryRun) tx.Rollback(); else tx.Commit(); return results;
    }
    static MasterDataImportResult Employees(AppDbContext db,IXLWorksheet ws){var m=Map(ws);int n=0,u=0;var errors=new List<string>();for(int r=2;r<=(ws.LastRowUsed()?.RowNumber()??1);r++){var no=C(ws,r,m,"Personalnummer");if(no=="")continue;try{var x=db.Employees.Include(x=>x.Qualifications).FirstOrDefault(x=>x.PersonnelNumber==no);if(x==null){x=new Employee{PersonnelNumber=no};db.Employees.Add(x);n++;}else u++;x.FirstName=Req(C(ws,r,m,"Vorname"),"Vorname");x.LastName=Req(C(ws,r,m,"Nachname"),"Nachname");x.Role=C(ws,r,m,"Funktion");x.Department=C(ws,r,m,"Abteilung");x.WorkloadPercent=Int(C(ws,r,m,"PensumProzent"),100);x.WeeklyTargetHours=Num(C(ws,r,m,"SollstundenWoche"),40);x.IsActive=Yes(C(ws,r,m,"Aktiv"));db.SaveChanges();var skills=C(ws,r,m,"Qualifikationen");if(skills!=""){foreach(var part in skills.Split(';',StringSplitOptions.RemoveEmptyEntries)){var p=part.Split(':',2);var qn=p[0].Trim();var level=p.Length>1?Int(p[1],0):2;var q=db.Qualifications.FirstOrDefault(q=>q.Name==qn);if(q==null){q=new Qualification{Name=qn};db.Qualifications.Add(q);db.SaveChanges();}var eq=db.EmployeeQualifications.FirstOrDefault(z=>z.EmployeeId==x.Id&&z.QualificationId==q.Id);if(level<=0){if(eq!=null)db.EmployeeQualifications.Remove(eq);}else if(eq==null)db.EmployeeQualifications.Add(new EmployeeQualification{EmployeeId=x.Id,QualificationId=q.Id,Level=Math.Clamp(level,1,3)});else eq.Level=Math.Clamp(level,1,3);}}db.SaveChanges();}}catch(Exception ex){errors.Add($"Zeile {r} ({no}): {ex.Message}");}}return new("Mitarbeitende",n,u,errors);}
    static MasterDataImportResult Workstations(AppDbContext db,IXLWorksheet ws){var m=Map(ws);int n=0,u=0;var errors=new List<string>();for(int r=2;r<=(ws.LastRowUsed()?.RowNumber()??1);r++){var name=C(ws,r,m,"Name");if(name=="")continue;try{var x=db.Workstations.FirstOrDefault(x=>x.Name==name);if(x==null){x=new Workstation{Name=name};db.Workstations.Add(x);n++;}else u++;x.Area=C(ws,r,m,"Bereich");x.MinimumStaff=Int(C(ws,r,m,"Minimum"),1);x.OptimalStaff=Int(C(ws,r,m,"Optimal"),Math.Max(1,x.MinimumStaff));x.MaximumStaff=Int(C(ws,r,m,"Maximum"),Math.Max(x.OptimalStaff,1));x.IsActive=Yes(C(ws,r,m,"Aktiv"));var qn=C(ws,r,m,"Pflichtqualifikation");if(qn!=""){var q=db.Qualifications.FirstOrDefault(q=>q.Name==qn)??new Qualification{Name=qn};if(q.Id==0){db.Qualifications.Add(q);db.SaveChanges();}x.RequiredQualificationId=q.Id;x.RequiredQualificationLevel=Math.Clamp(Int(C(ws,r,m,"SkillLevel"),2),1,3);}db.SaveChanges();}catch(Exception ex){errors.Add($"Zeile {r} ({name}): {ex.Message}");}}return new("Arbeitsplätze",n,u,errors);}
    static MasterDataImportResult Shifts(AppDbContext db,IXLWorksheet ws){var m=Map(ws);int n=0,u=0;var errors=new List<string>();for(int r=2;r<=(ws.LastRowUsed()?.RowNumber()??1);r++){var name=C(ws,r,m,"Name");if(name=="")continue;try{var x=db.Shifts.FirstOrDefault(x=>x.Name==name);if(x==null){x=new Shift{Name=name};db.Shifts.Add(x);n++;}else u++;x.StartTime=TimeSpan.Parse(Req(C(ws,r,m,"Start"),"Start"));x.EndTime=TimeSpan.Parse(Req(C(ws,r,m,"Ende"),"Ende"));x.BreakMinutes=Int(C(ws,r,m,"PauseMinuten"),0);db.SaveChanges();}catch(Exception ex){errors.Add($"Zeile {r} ({name}): {ex.Message}");}}return new("Schichten",n,u,errors);}
    static MasterDataImportResult Orders(AppDbContext db,IXLWorksheet ws){var m=Map(ws);int n=0,u=0;var errors=new List<string>();for(int r=2;r<=(ws.LastRowUsed()?.RowNumber()??1);r++){var no=C(ws,r,m,"Auftragsnummer");if(no=="")continue;try{var existing=db.ProductionOrders.FirstOrDefault(x=>x.OrderNumber==no);if(existing!=null){u++;continue;}var an=Req(C(ws,r,m,"Artikelnummer"),"Artikelnummer");var a=db.ArticleMasters.FirstOrDefault(x=>x.ArticleNumber==an&&x.IsActive)??throw new InvalidOperationException("Aktiver Artikel nicht gefunden.");var wn=Req(C(ws,r,m,"Arbeitsplatz"),"Arbeitsplatz");var sn=Req(C(ws,r,m,"Schicht"),"Schicht");var w=db.Workstations.FirstOrDefault(x=>x.Name==wn&&x.IsActive)??throw new InvalidOperationException("Aktiver Arbeitsplatz nicht gefunden.");var sh=db.Shifts.FirstOrDefault(x=>x.Name==sn)??throw new InvalidOperationException("Schicht nicht gefunden.");var date=DateTime.Parse(Req(C(ws,r,m,"Datum"),"Datum")).Date;var count=Math.Max(1,Int(C(ws,r,m,"AnzahlSchichten"),1));if(ProductionScheduleService.BuildPreview(date,w.Id,sh.Id,count).Count!=count)throw new InvalidOperationException("Terminierung ist für Arbeitsplatz/Schicht nicht vollständig freigegeben.");var x=new ProductionOrder{OrderNumber=no,ArticleMasterId=a.Id,ArticleNumber=a.ArticleNumber,Product=a.Name,Unit=a.Unit,BatchNumber=Req(C(ws,r,m,"Chargennummer"),"Chargennummer"),Quantity=Num(C(ws,r,m,"Menge"),a.DefaultQuantity??1),PlannedDate=date,WorkstationId=w.Id,ShiftId=sh.Id,PlannedStart=sh.StartTime,PlannedEnd=sh.EndTime,PlannedShiftCount=count,RequiredStaff=Math.Max(1,Int(C(ws,r,m,"Personalbedarf"),w.OptimalStaff)),Priority=string.IsNullOrWhiteSpace(C(ws,r,m,"Priorität"))?"Normal":C(ws,r,m,"Priorität"),Status="Geplant",Comment=C(ws,r,m,"Kommentar")};db.ProductionOrders.Add(x);db.SaveChanges();ProductionScheduleService.SyncRunSlots(db,x);db.SaveChanges();n++;}catch(Exception ex){errors.Add($"Zeile {r} ({no}): {ex.Message}");}}return new("Produktionsaufträge",n,u,errors);}
    static void Header(IXLWorksheet w,params string[] h){for(int i=0;i<h.Length;i++){w.Cell(1,i+1).Value=h[i];w.Cell(1,i+1).Style.Font.Bold=true;}}
    static Dictionary<string,int> Map(IXLWorksheet w)=>w.Row(1).CellsUsed().ToDictionary(c=>c.GetString().Trim(),c=>c.Address.ColumnNumber,StringComparer.OrdinalIgnoreCase);
    static string C(IXLWorksheet w,int r,Dictionary<string,int> m,string n)=>m.TryGetValue(n,out var c)?w.Cell(r,c).GetFormattedString().Trim():"";
    static string Req(string v,string n)=>string.IsNullOrWhiteSpace(v)?throw new InvalidOperationException($"{n} fehlt."):v.Trim();
    static int Int(string v,int d)=>int.TryParse(v,out var n)?n:d; static double Num(string v,double d)=>double.TryParse(v,out var n)?n:d;
    static bool Yes(string v)=>string.IsNullOrWhiteSpace(v)||v.Equals("Ja",StringComparison.OrdinalIgnoreCase)||v=="1"||v.Equals("true",StringComparison.OrdinalIgnoreCase);
}