using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
namespace Produktionsplanung.App.Services;
public static class OeeAnalyticsService{
 public static OeeMetrics Calculate(double planned,double run,double total,double good,double rate){var a=planned>0?Math.Clamp(run/planned,0,1):0;var tq=rate>0&&run>0?rate*run/60d:0;var raw=tq>0?total/tq:0;var p=Math.Clamp(raw,0,1);var q=total>0?Math.Clamp(good/total,0,1):0;return new(){AvailabilityPercent=a*100,PerformancePercent=p*100,QualityPercent=q*100,OeePercent=a*p*q*100,TheoreticalQuantity=tq,RawPerformancePercent=raw*100};}
 public static OeePeriodSummary LoadPeriod(DateTime startDate,DateTime endDate){using var db=new AppDbContext();var start=startDate.Date;var end=endDate.Date;var actuals=db.ProductionActuals.AsNoTracking().Include(x=>x.ProductionOrder).ThenInclude(x=>x.Workstation).Include(x=>x.ProductionOrder).ThenInclude(x=>x.Shift).Include(x=>x.ProductionRunSlot).ThenInclude(x=>x!.Shift).Include(x=>x.Downtimes).Where(x=>x.Date.Date>=start&&x.Date.Date<=end).OrderBy(x=>x.Date).ToList();return Summarize(actuals);}
 public static OeePeriodSummary Summarize(IEnumerable<Produktionsplanung.App.Models.ProductionActual> actuals){var rows=actuals.Select(x=>{var m=Calculate(x.PlannedProductionMinutes,x.RunMinutes,x.TotalQuantity,x.GoodQuantity,x.IdealRatePerHour);return new OeeActualMetricRow{ActualId=x.Id,Date=x.Date.Date,OrderNumber=x.ProductionOrder.OrderNumber,Product=x.ProductionOrder.Product,WorkstationId=x.ProductionOrder.WorkstationId,WorkstationName=x.ProductionOrder.Workstation.Name,Unit=x.ProductionOrder.Unit,ShiftName=x.ProductionRunSlot?.Shift.Name??x.ProductionOrder.Shift?.Name??"Legacy / nicht eindeutig",TotalQuantity=x.TotalQuantity,GoodQuantity=x.GoodQuantity,ScrapQuantity=x.ScrapQuantity,PlannedProductionMinutes=x.PlannedProductionMinutes,RunMinutes=x.RunMinutes,DowntimeMinutes=x.Downtimes.Sum(d=>d.Minutes),IdealRatePerHour=x.IdealRatePerHour,AvailabilityPercent=m.AvailabilityPercent,PerformancePercent=m.PerformancePercent,QualityPercent=m.QualityPercent,OeePercent=m.OeePercent};}).ToList();var sm=Aggregate(rows);var ws=rows.GroupBy(x=>x.WorkstationId).Select(g=>{var m=Aggregate(g);return new OeeWorkstationRow{WorkstationId=g.Key,WorkstationName=g.First().WorkstationName,Records=g.Count(),TotalQuantityText=FormatQuantities(g,x=>x.TotalQuantity),GoodQuantityText=FormatQuantities(g,x=>x.GoodQuantity),ScrapQuantityText=FormatQuantities(g,x=>x.ScrapQuantity),DowntimeMinutes=g.Sum(x=>x.DowntimeMinutes),AvailabilityPercent=m.AvailabilityPercent,PerformancePercent=m.PerformancePercent,QualityPercent=m.QualityPercent,OeePercent=m.OeePercent};}).OrderBy(x=>x.WorkstationName).ToList();return new OeePeriodSummary{Records=rows.Count,TotalQuantityText=FormatQuantities(rows,x=>x.TotalQuantity),GoodQuantityText=FormatQuantities(rows,x=>x.GoodQuantity),ScrapQuantityText=FormatQuantities(rows,x=>x.ScrapQuantity),PlannedProductionMinutes=rows.Sum(x=>x.PlannedProductionMinutes),RunMinutes=rows.Sum(x=>x.RunMinutes),DowntimeMinutes=rows.Sum(x=>x.DowntimeMinutes),AvailabilityPercent=sm.AvailabilityPercent,PerformancePercent=sm.PerformancePercent,QualityPercent=sm.QualityPercent,OeePercent=sm.OeePercent,ActualRows=rows,WorkstationRows=ws};}
 private static OeeMetrics Aggregate(IEnumerable<OeeActualMetricRow> source){var r=source.ToList();var planned=r.Sum(x=>x.PlannedProductionMinutes);var run=r.Sum(x=>x.RunMinutes);var ideal=r.Sum(x=>x.IdealRatePerHour>0?x.TotalQuantity/x.IdealRatePerHour*60:0);var good=r.Sum(x=>x.IdealRatePerHour>0?x.GoodQuantity/x.IdealRatePerHour*60:0);var a=planned>0?Math.Clamp(run/planned,0,1):0;var p=run>0?Math.Clamp(ideal/run,0,1):0;var q=ideal>0?Math.Clamp(good/ideal,0,1):0;return new(){AvailabilityPercent=a*100,PerformancePercent=p*100,QualityPercent=q*100,OeePercent=a*p*q*100};}
 private static string FormatQuantities(IEnumerable<OeeActualMetricRow> rows,Func<OeeActualMetricRow,double> selector){var p=rows.GroupBy(x=>x.Unit).OrderBy(x=>x.Key).Select(g=>$"{g.Sum(selector):N2} {g.Key}").ToList();return p.Count==0?"—":string.Join(" · ",p);}
}
public class OeeMetrics{public double AvailabilityPercent{get;set;}public double PerformancePercent{get;set;}public double RawPerformancePercent{get;set;}public double QualityPercent{get;set;}public double OeePercent{get;set;}public double TheoreticalQuantity{get;set;}}
public class OeeActualMetricRow{public int WorkstationId{get;set;}public string Unit{get;set;}=string.Empty;public int ActualId{get;set;}public DateTime Date{get;set;}public string OrderNumber{get;set;}=string.Empty;public string Product{get;set;}=string.Empty;public string WorkstationName{get;set;}=string.Empty;public string ShiftName{get;set;}=string.Empty;public double TotalQuantity{get;set;}public double GoodQuantity{get;set;}public double ScrapQuantity{get;set;}public double PlannedProductionMinutes{get;set;}public double RunMinutes{get;set;}public double DowntimeMinutes{get;set;}public double IdealRatePerHour{get;set;}public double AvailabilityPercent{get;set;}public double PerformancePercent{get;set;}public double QualityPercent{get;set;}public double OeePercent{get;set;}public string OeeText=>$"{OeePercent:N1} %";}
public class OeeWorkstationRow{public int WorkstationId{get;set;}public string WorkstationName{get;set;}=string.Empty;public int Records{get;set;}public string TotalQuantityText{get;set;}="—";public string GoodQuantityText{get;set;}="—";public string ScrapQuantityText{get;set;}="—";public double DowntimeMinutes{get;set;}public double AvailabilityPercent{get;set;}public double PerformancePercent{get;set;}public double QualityPercent{get;set;}public double OeePercent{get;set;}public string AvailabilityText=>$"{AvailabilityPercent:N1} %";public string PerformanceText=>$"{PerformancePercent:N1} %";public string QualityText=>$"{QualityPercent:N1} %";public string OeeText=>$"{OeePercent:N1} %";}
public class OeePeriodSummary{public int Records{get;set;}public string TotalQuantityText{get;set;}="—";public string GoodQuantityText{get;set;}="—";public string ScrapQuantityText{get;set;}="—";public double PlannedProductionMinutes{get;set;}public double RunMinutes{get;set;}public double DowntimeMinutes{get;set;}public double AvailabilityPercent{get;set;}public double PerformancePercent{get;set;}public double QualityPercent{get;set;}public double OeePercent{get;set;}public List<OeeActualMetricRow> ActualRows{get;set;}=new();public List<OeeWorkstationRow> WorkstationRows{get;set;}=new();}
