using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
using Produktionsplanung.App.Models;
using Produktionsplanung.App.Services;
namespace Produktionsplanung.App.ViewModels;
public partial class DayPlanningViewModel:ObservableObject{
 public ObservableCollection<EmployeeOption> Employees{get;}=new();public ObservableCollection<WorkstationOption> Workstations{get;}=new();public ObservableCollection<ShiftOption> Shifts{get;}=new();public ObservableCollection<DayAssignmentRow> Assignments{get;}=new();public ObservableCollection<StaffingRow> Staffing{get;}=new();public ObservableCollection<PlanningAlert> Alerts{get;}=new();[ObservableProperty]private DateTime selectedDate=DateTime.Today;[ObservableProperty]private DayAssignmentRow? selectedAssignment;[ObservableProperty]private EmployeeOption? selectedEmployee;[ObservableProperty]private WorkstationOption? selectedWorkstation;[ObservableProperty]private ShiftOption? selectedShift;[ObservableProperty]private string comment=string.Empty;[ObservableProperty]private string statusMessage=string.Empty;private bool initialized;
 public DayPlanningViewModel(){LoadReferenceData();initialized=true;LoadDay();}public string SelectedDateText=>SelectedDate.ToString("dddd, dd.MM.yyyy");partial void OnSelectedDateChanged(DateTime value){OnPropertyChanged(nameof(SelectedDateText));if(initialized)LoadDay();}partial void OnSelectedAssignmentChanged(DayAssignmentRow? value){if(value is null)return;SelectedEmployee=Employees.FirstOrDefault(x=>x.Id==value.EmployeeId);SelectedWorkstation=Workstations.FirstOrDefault(x=>x.Id==value.WorkstationId);SelectedShift=Shifts.FirstOrDefault(x=>x.Id==value.ShiftId);Comment=value.Comment??"";StatusMessage="";}
 [RelayCommand]private void PreviousDay()=>SelectedDate=SelectedDate.AddDays(-1);[RelayCommand]private void Today()=>SelectedDate=DateTime.Today;[RelayCommand]private void NextDay()=>SelectedDate=SelectedDate.AddDays(1);[RelayCommand]private void Refresh(){LoadReferenceData();LoadDay(SelectedAssignment?.Id);StatusMessage="Planung aktualisiert.";}[RelayCommand]private void NewAssignment(){SelectedAssignment=null;ResetEditor();StatusMessage="";}
 [RelayCommand]private void Save(){if(SelectedEmployee is null){StatusMessage="Bitte einen Mitarbeiter auswählen.";return;}if(SelectedWorkstation is null){StatusMessage="Bitte einen Arbeitsplatz auswählen.";return;}if(SelectedShift is null){StatusMessage="Bitte eine Schicht auswählen.";return;}var ps=SelectedDate.Date+SelectedShift.StartTime;var pe=SelectedDate.Date+SelectedShift.EndTime;if(pe<=ps)pe=pe.AddDays(1);using var db=new AppDbContext();var employeeId=SelectedEmployee.Id;var editingId=SelectedAssignment?.Id;if(db.Absences.AsNoTracking().Any(x=>x.EmployeeId==employeeId&&x.StartDate.Date<=pe.Date&&x.EndDate.Date>=ps.Date)){StatusMessage=$"{SelectedEmployee.DisplayName} ist im gewählten Zeitraum als abwesend erfasst.";return;}var candidates=db.PlanningAssignments.AsNoTracking().Where(x=>x.EmployeeId==employeeId&&(!editingId.HasValue||x.Id!=editingId.Value)&&x.Date.Date>=SelectedDate.AddDays(-1).Date&&x.Date.Date<=SelectedDate.AddDays(1).Date).ToList();if(candidates.Any(x=>{var i=GetInterval(x.Date,x.StartTime,x.EndTime);return ps<i.End&&i.Start<pe;})){StatusMessage=$"Doppelbelegung: {SelectedEmployee.DisplayName} ist in diesem Zeitraum bereits eingeplant.";return;}PlanningAssignment e;if(SelectedAssignment is null){e=new();db.PlanningAssignments.Add(e);}else e=db.PlanningAssignments.First(x=>x.Id==SelectedAssignment.Id);e.EmployeeId=SelectedEmployee.Id;e.WorkstationId=SelectedWorkstation.Id;e.ShiftId=SelectedShift.Id;e.Date=SelectedDate.Date;e.StartTime=SelectedShift.StartTime;e.EndTime=SelectedShift.EndTime;e.BreakMinutes=SelectedShift.BreakMinutes;e.Comment=string.IsNullOrWhiteSpace(Comment)?null:Comment.Trim();db.SaveChanges();LoadDay(e.Id);StatusMessage="Zuweisung gespeichert.";}
 [RelayCommand]private void Delete(){if(SelectedAssignment is null){StatusMessage="Bitte zuerst eine Zuweisung auswählen.";return;}using var db=new AppDbContext();var e=db.PlanningAssignments.FirstOrDefault(x=>x.Id==SelectedAssignment.Id);if(e is null){LoadDay();return;}db.PlanningAssignments.Remove(e);db.SaveChanges();LoadDay();StatusMessage="Zuweisung gelöscht.";}
 private void LoadReferenceData(){using var db=new AppDbContext();var eid=SelectedEmployee?.Id;var wid=SelectedWorkstation?.Id;var sid=SelectedShift?.Id;Employees.Clear();foreach(var x in db.Employees.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.LastName).ThenBy(x=>x.FirstName))Employees.Add(new(){Id=x.Id,DisplayName=$"{x.LastName}, {x.FirstName}",Role=x.Role});Workstations.Clear();foreach(var x in db.Workstations.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name))Workstations.Add(new(){Id=x.Id,Name=x.Name});Shifts.Clear();foreach(var x in db.Shifts.AsNoTracking().AsEnumerable().OrderBy(x=>x.StartTime))Shifts.Add(new(){Id=x.Id,Name=x.Name,StartTime=x.StartTime,EndTime=x.EndTime,BreakMinutes=x.BreakMinutes});SelectedEmployee=Employees.FirstOrDefault(x=>x.Id==eid)??Employees.FirstOrDefault();SelectedWorkstation=Workstations.FirstOrDefault(x=>x.Id==wid)??Workstations.FirstOrDefault();SelectedShift=Shifts.FirstOrDefault(x=>x.Id==sid)??Shifts.FirstOrDefault();}
 private void LoadDay(int? selectId=null){using var db=new AppDbContext();var list=db.PlanningAssignments.AsNoTracking().Include(x=>x.Employee).Include(x=>x.Workstation).Include(x=>x.Shift).Where(x=>x.Date.Date==SelectedDate.Date).AsEnumerable().OrderBy(x=>x.Workstation.Name).ThenBy(x=>x.StartTime).ThenBy(x=>x.Employee.LastName).ToList();Assignments.Clear();foreach(var x in list)Assignments.Add(new(){Id=x.Id,EmployeeId=x.EmployeeId,WorkstationId=x.WorkstationId,ShiftId=x.ShiftId,EmployeeName=$"{x.Employee.LastName}, {x.Employee.FirstName}",Role=x.Employee.Role,WorkstationName=x.Workstation.Name,ShiftName=x.Shift?.Name??"Individuell",TimeText=$"{x.StartTime:hh\\:mm}–{x.EndTime:hh\\:mm}",Comment=x.Comment});BuildStaffing(list,db);BuildAlerts(list,db);SelectedAssignment=selectId.HasValue?Assignments.FirstOrDefault(x=>x.Id==selectId):null;if(SelectedAssignment is null)ResetEditor();RefreshEmployeeSuggestions();RefreshSkillAlerts();}
 private void BuildStaffing(List<PlanningAssignment> list,AppDbContext db){Staffing.Clear();var workstations=db.Workstations.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).ToList();var shiftMap=db.Shifts.AsNoTracking().AsEnumerable().ToDictionary(x=>x.Id);foreach(var w in workstations){var allowed=ProductionScheduleService.LoadAllowedShiftsForDate(db,w.Id,SelectedDate);foreach(var s in allowed){var p=list.Where(x=>x.WorkstationId==w.Id&&x.ShiftId==s.Id).Select(x=>x.EmployeeId).Distinct().Count();Staffing.Add(new(){WorkstationId=w.Id,WorkstationName=w.Name,ShiftName=s.Name,TimeText=$"{s.StartTime:hh\\:mm}–{s.EndTime:hh\\:mm}",PlannedStaff=p,MinimumStaff=w.MinimumStaff,OptimalStaff=w.OptimalStaff,MaximumStaff=w.MaximumStaff,StatusText=p<w.MinimumStaff?"Unterbesetzt":p<w.OptimalStaff?"Knapp besetzt":p>w.MaximumStaff?"Überbesetzt":"OK"});}foreach(var g in list.Where(x=>x.WorkstationId==w.Id&&(!x.ShiftId.HasValue||!allowed.Any(s=>s.Id==x.ShiftId.Value))).GroupBy(x=>new{x.ShiftId,x.StartTime,x.EndTime})){var p=g.Select(x=>x.EmployeeId).Distinct().Count();Staffing.Add(new(){WorkstationId=w.Id,WorkstationName=w.Name,ShiftName=g.First().Shift?.Name??"Individuell / nicht freigegeben",TimeText=$"{g.Key.StartTime:hh\\:mm}–{g.Key.EndTime:hh\\:mm}",PlannedStaff=p,MinimumStaff=w.MinimumStaff,OptimalStaff=w.OptimalStaff,MaximumStaff=w.MaximumStaff,StatusText="Nicht freigegeben"});}}}
 private void BuildAlerts(List<PlanningAssignment> list,AppDbContext db){Alerts.Clear();foreach(var r in Staffing){if(r.PlannedStaff<r.MinimumStaff)Alerts.Add(new(){Severity="Rot",Message=$"{r.WorkstationName} / {r.ShiftName} ist unterbesetzt: {r.PlannedStaff}/{r.MinimumStaff} Mindestbesetzung."});else if(r.PlannedStaff>r.MaximumStaff)Alerts.Add(new(){Severity="Gelb",Message=$"{r.WorkstationName} / {r.ShiftName} ist überbesetzt: {r.PlannedStaff}/{r.MaximumStaff}."});}if(list.Count==0)Alerts.Add(new(){Severity="Hinweis",Message="Für diesen Tag sind noch keine Mitarbeiter eingeplant."});var ids=list.Select(x=>x.EmployeeId).Distinct().ToList();var abs=db.Absences.AsNoTracking().Where(x=>ids.Contains(x.EmployeeId)&&x.StartDate.Date<=SelectedDate.AddDays(1)&&x.EndDate.Date>=SelectedDate).ToList();foreach(var a in list){var i=GetInterval(a.Date,a.StartTime,a.EndTime);if(abs.Any(x=>x.EmployeeId==a.EmployeeId&&x.StartDate.Date<=i.End.Date&&x.EndDate.Date>=i.Start.Date))Alerts.Add(new(){Severity="Rot",Message=$"{a.Employee.LastName}, {a.Employee.FirstName} ist eingeplant, aber abwesend."});if(!a.ShiftId.HasValue||!ProductionScheduleService.IsShiftAllowedOnDate(db,a.WorkstationId,a.ShiftId.Value,a.Date))Alerts.Add(new(){Severity="Rot",Message=$"{a.Workstation.Name} / {a.Shift?.Name??"Individuell"} ist an diesem Tag nicht freigegeben."});}}
 private void ResetEditor(){SelectedEmployee??=Employees.FirstOrDefault();SelectedWorkstation??=Workstations.FirstOrDefault();SelectedShift??=Shifts.FirstOrDefault();Comment="";}private static(DateTime Start,DateTime End)GetInterval(DateTime d,TimeSpan s,TimeSpan e){var a=d.Date+s;var b=d.Date+e;if(b<=a)b=b.AddDays(1);return(a,b);}
}
public class EmployeeOption{public int Id{get;set;}public string DisplayName{get;set;}=string.Empty;public string Role{get;set;}=string.Empty;}public class WorkstationOption{public int Id{get;set;}public string Name{get;set;}=string.Empty;}public class ShiftOption{public int Id{get;set;}public string Name{get;set;}=string.Empty;public TimeSpan StartTime{get;set;}public TimeSpan EndTime{get;set;}public int BreakMinutes{get;set;}public string DisplayName=>$"{Name} ({StartTime:hh\\:mm}–{EndTime:hh\\:mm})";}public class DayAssignmentRow{public int Id{get;set;}public int EmployeeId{get;set;}public int WorkstationId{get;set;}public int? ShiftId{get;set;}public string EmployeeName{get;set;}=string.Empty;public string Role{get;set;}=string.Empty;public string WorkstationName{get;set;}=string.Empty;public string ShiftName{get;set;}=string.Empty;public string TimeText{get;set;}=string.Empty;public string? Comment{get;set;}}public class StaffingRow{public int WorkstationId{get;set;}public string WorkstationName{get;set;}=string.Empty;public string ShiftName{get;set;}=string.Empty;public string TimeText{get;set;}=string.Empty;public int PlannedStaff{get;set;}public int MinimumStaff{get;set;}public int OptimalStaff{get;set;}public int MaximumStaff{get;set;}public string StatusText{get;set;}=string.Empty;}public class PlanningAlert{public string Severity{get;set;}=string.Empty;public string Message{get;set;}=string.Empty;}
