using System.Collections.ObjectModel;
using System.Windows;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
using Produktionsplanung.App.Models;
namespace Produktionsplanung.App.ViewModels;
public partial class EmployeeManagementViewModel:ObservableObject{
 private List<Employee> _allEmployees=new();public ObservableCollection<Employee> Employees{get;}=new();[ObservableProperty]private Employee? selectedEmployee;[ObservableProperty]private string searchText=string.Empty;[ObservableProperty]private bool showInactive;[ObservableProperty]private int editingId;[ObservableProperty]private string personnelNumber=string.Empty;[ObservableProperty]private string firstName=string.Empty;[ObservableProperty]private string lastName=string.Empty;[ObservableProperty]private string role=string.Empty;[ObservableProperty]private string department=string.Empty;[ObservableProperty]private int workloadPercent=100;[ObservableProperty]private double weeklyTargetHours=40;[ObservableProperty]private bool isActive=true;public string EditorTitle=>EditingId==0?"Neuer Mitarbeiter":$"Mitarbeiter bearbeiten – {FirstName} {LastName}";public EmployeeManagementViewModel(){LoadEmployees();NewEmployee();}partial void OnSearchTextChanged(string v)=>ApplyFilter();partial void OnShowInactiveChanged(bool v)=>ApplyFilter();partial void OnSelectedEmployeeChanged(Employee? v){if(v is null)return;EditingId=v.Id;PersonnelNumber=v.PersonnelNumber;FirstName=v.FirstName;LastName=v.LastName;Role=v.Role;Department=v.Department;WorkloadPercent=v.WorkloadPercent;WeeklyTargetHours=v.WeeklyTargetHours;IsActive=v.IsActive;OnPropertyChanged(nameof(EditorTitle));}
 [RelayCommand]private void NewEmployee(){SelectedEmployee=null;EditingId=0;PersonnelNumber=FirstName=LastName=Role="";Department="Produktion";WorkloadPercent=100;WeeklyTargetHours=40;IsActive=true;OnPropertyChanged(nameof(EditorTitle));}[RelayCommand]private void Save(){PersonnelNumber=PersonnelNumber.Trim();FirstName=FirstName.Trim();LastName=LastName.Trim();Role=Role.Trim();Department=Department.Trim();if(string.IsNullOrWhiteSpace(PersonnelNumber)||string.IsNullOrWhiteSpace(FirstName)||string.IsNullOrWhiteSpace(LastName)){MessageBox.Show("Personalnummer, Vorname und Nachname sind Pflichtfelder.","Eingabe prüfen");return;}if(WorkloadPercent is<1 or>100){MessageBox.Show("Das Pensum muss zwischen 1 und 100 % liegen.","Eingabe prüfen");return;}if(!double.IsFinite(WeeklyTargetHours)||WeeklyTargetHours is<0 or>80){MessageBox.Show("Die Sollstunden müssen eine gültige Zahl zwischen 0 und 80 Stunden sein.","Eingabe prüfen");return;}using var db=new AppDbContext();if(db.Employees.Any(x=>x.PersonnelNumber==PersonnelNumber&&x.Id!=EditingId)){MessageBox.Show($"Die Personalnummer {PersonnelNumber} ist bereits vergeben.","Doppelte Personalnummer");return;}Employee e;if(EditingId==0){e=new();db.Employees.Add(e);}else e=db.Employees.First(x=>x.Id==EditingId);e.PersonnelNumber=PersonnelNumber;e.FirstName=FirstName;e.LastName=LastName;e.Role=Role;e.Department=Department;e.WorkloadPercent=WorkloadPercent;e.WeeklyTargetHours=WeeklyTargetHours;e.IsActive=IsActive;db.SaveChanges();var id=e.Id;LoadEmployees();SelectedEmployee=Employees.FirstOrDefault(x=>x.Id==id);}
 [RelayCommand]private void Deactivate(){if(EditingId==0)return;if(MessageBox.Show($"{FirstName} {LastName} wirklich deaktivieren?","Mitarbeiter deaktivieren",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return;using var db=new AppDbContext();db.Employees.First(x=>x.Id==EditingId).IsActive=false;db.SaveChanges();LoadEmployees();NewEmployee();}[RelayCommand]private void Activate(){if(EditingId==0)return;using var db=new AppDbContext();db.Employees.First(x=>x.Id==EditingId).IsActive=true;db.SaveChanges();LoadEmployees();SelectedEmployee=Employees.FirstOrDefault(x=>x.Id==EditingId);}
 [RelayCommand]private void Delete(){if(EditingId==0)return;using var db=new AppDbContext();var refs=new List<string>();if(db.PlanningAssignments.Any(x=>x.EmployeeId==EditingId))refs.Add("Planungen");if(db.Absences.Any(x=>x.EmployeeId==EditingId))refs.Add("Abwesenheiten");if(db.WorkTimeEntries.Any(x=>x.EmployeeId==EditingId))refs.Add("Arbeitszeitbuchungen");if(refs.Count>0){MessageBox.Show($"Dieser Mitarbeiter kann nicht endgültig gelöscht werden, weil folgende Daten vorhanden sind: {string.Join(", ",refs)}. Bitte deaktivieren Sie ihn stattdessen.","Löschen nicht möglich",MessageBoxButton.OK,MessageBoxImage.Information);return;}if(MessageBox.Show($"{FirstName} {LastName} endgültig löschen? Dieser Vorgang kann nicht rückgängig gemacht werden.","Mitarbeiter löschen",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;db.EmployeeQualifications.RemoveRange(db.EmployeeQualifications.Where(x=>x.EmployeeId==EditingId));db.Employees.Remove(db.Employees.First(x=>x.Id==EditingId));try{db.SaveChanges();LoadEmployees();NewEmployee();}catch(DbUpdateException){MessageBox.Show("Der Mitarbeiter wird noch von anderen Daten verwendet und konnte nicht gelöscht werden. Bitte deaktivieren Sie ihn stattdessen.","Löschen nicht möglich",MessageBoxButton.OK,MessageBoxImage.Information);}}
 [RelayCommand]private void Refresh()=>LoadEmployees();private void LoadEmployees(){using var db=new AppDbContext();_allEmployees=db.Employees.AsNoTracking().OrderBy(x=>x.LastName).ThenBy(x=>x.FirstName).ToList();ApplyFilter();}private void ApplyFilter(){var q=_allEmployees.AsEnumerable();if(!ShowInactive)q=q.Where(x=>x.IsActive);if(!string.IsNullOrWhiteSpace(SearchText)){var t=SearchText.Trim();q=q.Where(x=>x.PersonnelNumber.Contains(t,StringComparison.OrdinalIgnoreCase)||x.FirstName.Contains(t,StringComparison.OrdinalIgnoreCase)||x.LastName.Contains(t,StringComparison.OrdinalIgnoreCase)||x.Role.Contains(t,StringComparison.OrdinalIgnoreCase)||x.Department.Contains(t,StringComparison.OrdinalIgnoreCase));}Employees.Clear();foreach(var e in q)Employees.Add(e);}}
