using System.Collections.ObjectModel;
using System.Globalization;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
using Produktionsplanung.App.Models;
namespace Produktionsplanung.App.ViewModels;
public partial class ShiftManagementViewModel:ObservableObject{
 public ObservableCollection<Shift> Shifts{get;}=new();[ObservableProperty]private Shift? selectedShift;[ObservableProperty]private string name=string.Empty;[ObservableProperty]private string startTimeText="06:00";[ObservableProperty]private string endTimeText="14:00";[ObservableProperty]private int breakMinutes=30;[ObservableProperty]private string statusMessage=string.Empty;public ShiftManagementViewModel()=>Load();partial void OnSelectedShiftChanged(Shift? v){if(v is null)return;Name=v.Name;StartTimeText=v.StartTime.ToString(@"hh\:mm");EndTimeText=v.EndTime.ToString(@"hh\:mm");BreakMinutes=v.BreakMinutes;StatusMessage="";}[RelayCommand]private void NewShift(){SelectedShift=null;Name="";StartTimeText="06:00";EndTimeText="14:00";BreakMinutes=30;StatusMessage="";}
 [RelayCommand]private void Save(){if(string.IsNullOrWhiteSpace(Name)){StatusMessage="Bitte einen Schichtnamen eingeben.";return;}if(!TryParseClock(StartTimeText,out var start)||!TryParseClock(EndTimeText,out var end)){StatusMessage="Zeit bitte exakt im Format HH:mm zwischen 00:00 und 23:59 eingeben.";return;}if(start==end){StatusMessage="Start- und Endzeit dürfen nicht identisch sein. Eine 24-Stunden-Schicht muss ausdrücklich in mehrere Schichten aufgeteilt werden.";return;}var duration=end-start;if(duration<=TimeSpan.Zero)duration+=TimeSpan.FromDays(1);if(BreakMinutes<0){StatusMessage="Die Pause darf nicht negativ sein.";return;}if(BreakMinutes>=duration.TotalMinutes){StatusMessage=$"Die Pause muss kürzer als die Schichtdauer von {duration.TotalMinutes:N0} Minuten sein.";return;}if(duration.TotalMinutes-BreakMinutes<15){StatusMessage="Nach Abzug der Pause müssen mindestens 15 Minuten Arbeitszeit verbleiben.";return;}using var db=new AppDbContext();Shift e;if(SelectedShift is null){e=new();db.Shifts.Add(e);}else e=db.Shifts.First(x=>x.Id==SelectedShift.Id);e.Name=Name.Trim();e.StartTime=start;e.EndTime=end;e.BreakMinutes=BreakMinutes;db.SaveChanges();Load(e.Id);StatusMessage="Schicht gespeichert.";}
 [RelayCommand]private void Delete(){if(SelectedShift is null)return;using var db=new AppDbContext();var id=SelectedShift.Id;var refs=new List<string>();if(db.PlanningAssignments.Any(x=>x.ShiftId==id))refs.Add("Mitarbeiterplanungen");if(db.ProductionRunSlots.Any(x=>x.ShiftId==id))refs.Add("Produktionsläufe");if(db.ProductionOrders.Any(x=>x.ShiftId==id))refs.Add("Produktionsaufträge");if(db.WorkstationShiftRules.Any(x=>x.ShiftId==id))refs.Add("Arbeitsplatz-Schichtregeln");if(refs.Count>0){StatusMessage=$"Schicht kann nicht gelöscht werden: verwendet in {string.Join(", ",refs)}.";return;}db.Shifts.Remove(db.Shifts.First(x=>x.Id==id));try{db.SaveChanges();Load();NewShift();StatusMessage="Schicht gelöscht.";}catch(DbUpdateException){StatusMessage="Schicht wird noch von anderen Daten verwendet und konnte nicht gelöscht werden.";}}
 private static bool TryParseClock(string text,out TimeSpan value){value=default;if(string.IsNullOrWhiteSpace(text))return false;return TimeSpan.TryParseExact(text.Trim(),@"hh\:mm",CultureInfo.InvariantCulture,out value)&&value>=TimeSpan.Zero&&value<TimeSpan.FromDays(1);}private void Load(int? selectId=null){using var db=new AppDbContext();var items=db.Shifts.AsNoTracking().AsEnumerable().OrderBy(x=>x.StartTime).ToList();Shifts.Clear();foreach(var i in items)Shifts.Add(i);SelectedShift=selectId is null?null:Shifts.FirstOrDefault(x=>x.Id==selectId);}}
