using System.Collections.ObjectModel;
using System.Globalization;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
using Produktionsplanung.App.Models;
using Produktionsplanung.App.Services;
namespace Produktionsplanung.App.ViewModels;
public partial class WeekPlanningViewModel:ObservableObject{
 public ObservableCollection<EmployeeWeekRow> EmployeeRows{get;}=new();public ObservableCollection<WeekStaffingRow> StaffingRows{get;}=new();public ObservableCollection<PlanningAlert> Alerts{get;}=new();[ObservableProperty]private DateTime weekStart=GetMonday(DateTime.Today);[ObservableProperty]private string statusMessage=string.Empty;private bool initialized;public WeekPlanningViewModel(){initialized=true;LoadWeek();}public string WeekRangeText{get{var e=WeekStart.AddDays(6);return $"KW {ISOWeek.GetWeekOfYear(WeekStart)} · {WeekStart:dd.MM.yyyy}–{e:dd.MM.yyyy}";}}public string MondayHeader=>$"Mo\n{WeekStart:dd.MM.}";public string TuesdayHeader=>$"Di\n{WeekStart.AddDays(1):dd.MM.}";public string WednesdayHeader=>$"Mi\n{WeekStart.AddDays(2):dd.MM.}";public string ThursdayHeader=>$"Do\n{WeekStart.AddDays(3):dd.MM.}";public string FridayHeader=>$"Fr\n{WeekStart.AddDays(4):dd.MM.}";public string SaturdayHeader=>$"Sa\n{WeekStart.AddDays(5):dd.MM.}";public string SundayHeader=>$"So\n{WeekStart.AddDays(6):dd.MM.}";
 partial void OnWeekStartChanged(DateTime v){var m=GetMonday(v);if(v.Date!=m){WeekStart=m;return;}OnPropertyChanged(nameof(WeekRangeText));OnPropertyChanged(nameof(MondayHeader));OnPropertyChanged(nameof(TuesdayHeader));OnPropertyChanged(nameof(WednesdayHeader));OnPropertyChanged(nameof(ThursdayHeader));OnPropertyChanged(nameof(FridayHeader));OnPropertyChanged(nameof(SaturdayHeader));OnPropertyChanged(nameof(SundayHeader));if(initialized)LoadWeek();}[RelayCommand]private void PreviousWeek()=>WeekStart=WeekStart.AddDays(-7);[RelayCommand]private void CurrentWeek()=>WeekStart=GetMonday(DateTime.Today);[RelayCommand]private void NextWeek()=>WeekStart=WeekStart.AddDays(7);[RelayCommand]private void Refresh(){LoadWeek();StatusMessage="Wochenplanung aktualisiert.";}
 [RelayCommand]private void CopyPreviousWeek(){using var db=new AppDbContext();var ts=WeekStart.Date;var te=ts.AddDays(6);var ss=ts.AddDays(-7);var se=te.AddDays(-7);var source=db.PlanningAssignments.AsNoTracking().Where(x=>x.Date.Date>=ss&&x.Date.Date<=se).AsEnumerable().OrderBy(x=>x.Date).ThenBy(x=>x.StartTime).ToList();if(source.Count==0){StatusMessage="In der Vorwoche gibt es keine Planungen zum Kopieren.";return;}var activeE=db.Employees.AsNoTracking().Where(x=>x.IsActive).Select(x=>x.Id).ToHashSet();var activeW=db.Workstations.AsNoTracking().Where(x=>x.IsActive).Select(x=>x.Id).ToHashSet();var abs=db.Absences.AsNoTracking().Where(x=>x.StartDate.Date<=te.AddDays(1)&&x.EndDate.Date>=ts.AddDays(-1)).ToList();var existing=db.PlanningAssignments.AsNoTracking().Where(x=>x.Date.Date>=ts.AddDays(-1)&&x.Date.Date<=te.AddDays(1)).ToList();var accepted=new List<PlanningAssignment>();int copied=0,skipped=0,skill=0,conflict=0,rule=0;foreach(var item in source){var d=item.Date.Date.AddDays(7);if(!activeE.Contains(item.EmployeeId)||!activeW.Contains(item.WorkstationId)){skipped++;continue;}if(!item.ShiftId.HasValue||!ProductionScheduleService.IsShiftAllowedOnDate(db,item.WorkstationId,item.ShiftId.Value,d)){rule++;continue;}var candidate=GetInterval(d,item.StartTime,item.EndTime);if(abs.Any(x=>x.EmployeeId==item.EmployeeId&&x.StartDate.Date<=candidate.End.Date&&x.EndDate.Date>=candidate.Start.Date)){skipped++;continue;}if(!QualificationPlanningService.CheckEmployee(db,item.EmployeeId,item.WorkstationId).IsQualified){skill++;continue;}if(existing.Any(x=>x.EmployeeId==item.EmployeeId&&Overlap(candidate,GetInterval(x.Date,x.StartTime,x.EndTime)))||accepted.Any(x=>x.EmployeeId==item.EmployeeId&&Overlap(candidate,GetInterval(x.Date,x.StartTime,x.EndTime)))){conflict++;continue;}var c=new PlanningAssignment{EmployeeId=item.EmployeeId,WorkstationId=item.WorkstationId,ShiftId=item.ShiftId,Date=d,StartTime=item.StartTime,EndTime=item.EndTime,BreakMinutes=item.BreakMinutes,Comment=item.Comment};db.PlanningAssignments.Add(c);accepted.Add(c);copied++;}db.SaveChanges();LoadWeek();StatusMessage=$"Vorwoche kopiert: {copied}; {skipped} Abwesenheit/inaktiv, {skill} Qualifikation, {conflict} Überschneidung, {rule} Schichtregel übersprungen.";}
 private void LoadWeek(){using var db=new AppDbContext();var end=WeekStart.AddDays(6).Date;var employees=db.Employees.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.LastName).ThenBy(x=>x.FirstName).ToList();var a=db.PlanningAssignments.AsNoTracking().Include(x=>x.Employee).Include(x=>x.Workstation).Include(x=>x.Shift).Where(x=>x.Date.Date>=WeekStart.Date&&x.Date.Date<=end).AsEnumerable().OrderBy(x=>x.Date).ThenBy(x=>x.StartTime).ToList();var abs=db.Absences.AsNoTracking().Where(x=>x.StartDate.Date<=end.AddDays(1)&&x.EndDate.Date>=WeekStart.Date).ToList();EmployeeRows.Clear();foreach(var e in employees)EmployeeRows.Add(new(){EmployeeId=e.Id,EmployeeName=$"{e.LastName}, {e.FirstName}",Role=e.Role,Monday=Cell(e.Id,WeekStart,a,abs),Tuesday=Cell(e.Id,WeekStart.AddDays(1),a,abs),Wednesday=Cell(e.Id,WeekStart.AddDays(2),a,abs),Thursday=Cell(e.Id,WeekStart.AddDays(3),a,abs),Friday=Cell(e.Id,WeekStart.AddDays(4),a,abs),Saturday=Cell(e.Id,WeekStart.AddDays(5),a,abs),Sunday=Cell(e.Id,WeekStart.AddDays(6),a,abs)});BuildStaffing(a,db);BuildAlerts(a,abs,db);}
 private static string Cell(int id,DateTime day,List<PlanningAssignment>a,List<Absence>abs){var items=a.Where(x=>x.EmployeeId==id&&x.Date.Date==day.Date).OrderBy(x=>x.StartTime);var parts=new List<string>();var ab=abs.FirstOrDefault(x=>x.EmployeeId==id&&x.StartDate.Date<=day.Date&&x.EndDate.Date>=day.Date);if(ab is not null)parts.Add($"ABW: {ab.Type}");foreach(var x in items)parts.Add($"{x.Workstation.Name} · {x.Shift?.Name??"Individuell"}\n{x.StartTime:hh\\:mm}–{x.EndTime:hh\\:mm}");return parts.Count==0?"—":string.Join("\n",parts);}
 private void BuildStaffing(List<PlanningAssignment>a,AppDbContext db){StaffingRows.Clear();var ws=db.Workstations.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).ToList();for(var n=0;n<7;n++){var day=WeekStart.AddDays(n).Date;foreach(var w in ws){var allowed=ProductionScheduleService.LoadAllowedShiftsForDate(db,w.Id,day);foreach(var s in allowed){var p=a.Where(x=>x.Date.Date==day&&x.WorkstationId==w.Id&&x.ShiftId==s.Id).Select(x=>x.EmployeeId).Distinct().Count();StaffingRows.Add(Row(day,w,s.Name,s.StartTime,s.EndTime,p));}foreach(var g in a.Where(x=>x.Date.Date==day&&x.WorkstationId==w.Id&&(!x.ShiftId.HasValue||!allowed.Any(s=>s.Id==x.ShiftId.Value))).GroupBy(x=>new{x.ShiftId,x.StartTime,x.EndTime})){var p=g.Select(x=>x.EmployeeId).Distinct().Count();StaffingRows.Add(Row(day,w,g.First().Shift?.Name??"Individuell / nicht freigegeben",g.Key.StartTime,g.Key.EndTime,p,"Nicht freigegeben"));}}}}
 private static WeekStaffingRow Row(DateTime day,Workstation w,string shift,TimeSpan start,TimeSpan end,int p,string? forced=null)=>new(){Date=day,DayText=day.ToString("ddd dd.MM.",CultureInfo.GetCultureInfo("de-CH")),WorkstationName=w.Name,ShiftName=shift,TimeText=$"{start:hh\\:mm}–{end:hh\\:mm}",PlannedStaff=p,MinimumStaff=w.MinimumStaff,OptimalStaff=w.OptimalStaff,MaximumStaff=w.MaximumStaff,StatusText=forced??(p<w.MinimumStaff?"Unterbesetzt":p<w.OptimalStaff?"Knapp besetzt":p>w.MaximumStaff?"Überbesetzt":"OK")};
 private void BuildAlerts(List<PlanningAssignment>a,List<Absence>abs,AppDbContext db){Alerts.Clear();foreach(var r in StaffingRows){if(r.PlannedStaff<r.MinimumStaff)Alerts.Add(new(){Severity="Rot",Message=$"{r.DayText}: {r.WorkstationName} / {r.ShiftName} unterbesetzt ({r.PlannedStaff}/{r.MinimumStaff})."});else if(r.PlannedStaff>r.MaximumStaff)Alerts.Add(new(){Severity="Gelb",Message=$"{r.DayText}: {r.WorkstationName} / {r.ShiftName} überbesetzt ({r.PlannedStaff}/{r.MaximumStaff})."});}foreach(var x in a){var i=GetInterval(x.Date,x.StartTime,x.EndTime);var absence=abs.FirstOrDefault(z=>z.EmployeeId==x.EmployeeId&&z.StartDate.Date<=i.End.Date&&z.EndDate.Date>=i.Start.Date);if(absence is not null)Alerts.Add(new(){Severity="Rot",Message=$"{x.Date:ddd dd.MM.}: {x.Employee.LastName}, {x.Employee.FirstName} ist eingeplant, aber als {absence.Type} abwesend."});var sk=QualificationPlanningService.CheckEmployee(db,x.EmployeeId,x.WorkstationId);if(!sk.IsQualified)Alerts.Add(new(){Severity="Rot",Message=$"{x.Date:ddd dd.MM.}: {x.Employee.LastName}, {x.Employee.FirstName} erfüllt die Pflichtqualifikation für {x.Workstation.Name} nicht."});if(!x.ShiftId.HasValue||!ProductionScheduleService.IsShiftAllowedOnDate(db,x.WorkstationId,x.ShiftId.Value,x.Date))Alerts.Add(new(){Severity="Rot",Message=$"{x.Date:ddd dd.MM.}: {x.Workstation.Name} / {x.Shift?.Name??"Individuell"} ist nicht freigegeben."});}if(a.Count==0)Alerts.Add(new(){Severity="Hinweis",Message="Für diese Woche sind noch keine Einsätze geplant."});}
 private static bool Overlap((DateTime Start,DateTime End)a,(DateTime Start,DateTime End)b)=>a.Start<b.End&&b.Start<a.End;private static DateTime GetMonday(DateTime d){var x=(7+((int)d.DayOfWeek-(int)DayOfWeek.Monday))%7;return d.Date.AddDays(-x);}private static(DateTime Start,DateTime End)GetInterval(DateTime d,TimeSpan s,TimeSpan e){var a=d.Date+s;var b=d.Date+e;if(b<=a)b=b.AddDays(1);return(a,b);}
}
public class EmployeeWeekRow{public int EmployeeId{get;set;}public string EmployeeName{get;set;}=string.Empty;public string Role{get;set;}=string.Empty;public string Monday{get;set;}=string.Empty;public string Tuesday{get;set;}=string.Empty;public string Wednesday{get;set;}=string.Empty;public string Thursday{get;set;}=string.Empty;public string Friday{get;set;}=string.Empty;public string Saturday{get;set;}=string.Empty;public string Sunday{get;set;}=string.Empty;}public class WeekStaffingRow{public DateTime Date{get;set;}public string DayText{get;set;}=string.Empty;public string WorkstationName{get;set;}=string.Empty;public string ShiftName{get;set;}=string.Empty;public string TimeText{get;set;}=string.Empty;public int PlannedStaff{get;set;}public int MinimumStaff{get;set;}public int OptimalStaff{get;set;}public int MaximumStaff{get;set;}public string StatusText{get;set;}=string.Empty;}
