using System.Collections.ObjectModel;
using System.Globalization;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore;
using Produktionsplanung.App.Data;
using Produktionsplanung.App.Models;
using Produktionsplanung.App.Services;
namespace Produktionsplanung.App.ViewModels;
public partial class WeekPlanningViewModel:ObservableObject{
 public ObservableCollection<EmployeeWeekRow> EmployeeRows{get;}=new();public ObservableCollection<WeekStaffingRow> StaffingRows{get;}=new();public ObservableCollection<PlanningAlert> Alerts{get;}=new();[ObservableProperty]private DateTime weekStart=GetMonday(DateTime.Today);[ObservableProperty]private string statusMessage=string.Empty;private bool initialized;
 public WeekPlanningViewModel(){initialized=true;LoadWeek();} public string WeekRangeText{get{var e=WeekStart.AddDays(6);return $"KW {ISOWeek.GetWeekOfYear(WeekStart)} · {WeekStart:dd.MM.yyyy}–{e:dd.MM.yyyy}";}} public string MondayHeader=>$"Mo\n{WeekStart:dd.MM.}";public string TuesdayHeader=>$"Di\n{WeekStart.AddDays(1):dd.MM.}";public string WednesdayHeader=>$"Mi\n{WeekStart.AddDays(2):dd.MM.}";public string ThursdayHeader=>$"Do\n{WeekStart.AddDays(3):dd.MM.}";public string FridayHeader=>$"Fr\n{WeekStart.AddDays(4):dd.MM.}";public string SaturdayHeader=>$"Sa\n{WeekStart.AddDays(5):dd.MM.}";public string SundayHeader=>$"So\n{WeekStart.AddDays(6):dd.MM.}";
 partial void OnWeekStartChanged(DateTime value){var m=GetMonday(value);if(value.Date!=m){WeekStart=m;return;}OnPropertyChanged(nameof(WeekRangeText));OnPropertyChanged(nameof(MondayHeader));OnPropertyChanged(nameof(TuesdayHeader));OnPropertyChanged(nameof(WednesdayHeader));OnPropertyChanged(nameof(ThursdayHeader));OnPropertyChanged(nameof(FridayHeader));OnPropertyChanged(nameof(SaturdayHeader));OnPropertyChanged(nameof(SundayHeader));if(initialized)LoadWeek();}
 [RelayCommand]private void PreviousWeek()=>WeekStart=WeekStart.AddDays(-7);[RelayCommand]private void CurrentWeek()=>WeekStart=GetMonday(DateTime.Today);[RelayCommand]private void NextWeek()=>WeekStart=WeekStart.AddDays(7);[RelayCommand]private void Refresh(){LoadWeek();StatusMessage="Wochenplanung aktualisiert.";}
 [RelayCommand]private void CopyPreviousWeek(){using var db=new AppDbContext();var targetStart=WeekStart.Date;var targetEnd=targetStart.AddDays(6);var sourceStart=targetStart.AddDays(-7);var sourceEnd=targetEnd.AddDays(-7);var source=db.PlanningAssignments.AsNoTracking().Where(x=>x.Date.Date>=sourceStart&&x.Date.Date<=sourceEnd).AsEnumerable().OrderBy(x=>x.Date).ThenBy(x=>x.StartTime).ToList();if(source.Count==0){StatusMessage="In der Vorwoche gibt es keine Planungen zum Kopieren.";return;}var activeEmployeeIds=db.Employees.AsNoTracking().Where(x=>x.IsActive).Select(x=>x.Id).ToHashSet();var activeWorkstationIds=db.Workstations.AsNoTracking().Where(x=>x.IsActive).Select(x=>x.Id).ToHashSet();var absences=db.Absences.AsNoTracking().Where(x=>x.StartDate.Date<=targetEnd.AddDays(1)&&x.EndDate.Date>=targetStart.AddDays(-1)).ToList();var boundaryExisting=db.PlanningAssignments.AsNoTracking().Where(x=>x.Date.Date>=targetStart.AddDays(-1)&&x.Date.Date<=targetEnd.AddDays(1)).ToList();var accepted=new List<PlanningAssignment>();var copied=0;var skipped=0;var skippedSkill=0;var skippedConflict=0;
 foreach(var item in source){var targetDate=item.Date.Date.AddDays(7);if(!activeEmployeeIds.Contains(item.EmployeeId)||!activeWorkstationIds.Contains(item.WorkstationId)){skipped++;continue;}var candidate=GetInterval(targetDate,item.StartTime,item.EndTime);var absent=absences.Any(x=>x.EmployeeId==item.EmployeeId&&x.StartDate.Date<=candidate.End.Date&&x.EndDate.Date>=candidate.Start.Date);if(absent){skipped++;continue;}var skillCheck=QualificationPlanningService.CheckEmployee(db,item.EmployeeId,item.WorkstationId);if(!skillCheck.IsQualified){skippedSkill++;continue;}var conflict=boundaryExisting.Any(x=>x.EmployeeId==item.EmployeeId&&IntervalsOverlap(candidate,GetInterval(x.Date,x.StartTime,x.EndTime)))||accepted.Any(x=>x.EmployeeId==item.EmployeeId&&IntervalsOverlap(candidate,GetInterval(x.Date,x.StartTime,x.EndTime)));if(conflict){skippedConflict++;continue;}var copy=new PlanningAssignment{EmployeeId=item.EmployeeId,WorkstationId=item.WorkstationId,ShiftId=item.ShiftId,Date=targetDate,StartTime=item.StartTime,EndTime=item.EndTime,BreakMinutes=item.BreakMinutes,Comment=item.Comment};db.PlanningAssignments.Add(copy);accepted.Add(copy);copied++;}
 db.SaveChanges();LoadWeek();StatusMessage=$"Vorwoche kopiert: {copied} Einsätze; {skipped} wegen Abwesenheit/inaktiven Stammdaten, {skippedSkill} wegen Qualifikation und {skippedConflict} wegen Zeitüberschneidung übersprungen.";}
 private static bool IntervalsOverlap((DateTime Start,DateTime End)a,(DateTime Start,DateTime End)b)=>a.Start<b.End&&b.Start<a.End;
 private void LoadWeek(){using var db=new AppDbContext();var weekEnd=WeekStart.AddDays(6).Date;var employees=db.Employees.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.LastName).ThenBy(x=>x.FirstName).ToList();var assignments=db.PlanningAssignments.AsNoTracking().Include(x=>x.Employee).Include(x=>x.Workstation).Include(x=>x.Shift).Where(x=>x.Date.Date>=WeekStart.Date&&x.Date.Date<=weekEnd).AsEnumerable().OrderBy(x=>x.Date).ThenBy(x=>x.StartTime).ToList();var absences=db.Absences.AsNoTracking().Where(x=>x.StartDate.Date<=weekEnd.AddDays(1)&&x.EndDate.Date>=WeekStart.Date).ToList();EmployeeRows.Clear();foreach(var e in employees)EmployeeRows.Add(new EmployeeWeekRow{EmployeeId=e.Id,EmployeeName=$"{e.LastName}, {e.FirstName}",Role=e.Role,Monday=BuildDayCell(e.Id,WeekStart,assignments,absences),Tuesday=BuildDayCell(e.Id,WeekStart.AddDays(1),assignments,absences),Wednesday=BuildDayCell(e.Id,WeekStart.AddDays(2),assignments,absences),Thursday=BuildDayCell(e.Id,WeekStart.AddDays(3),assignments,absences),Friday=BuildDayCell(e.Id,WeekStart.AddDays(4),assignments,absences),Saturday=BuildDayCell(e.Id,WeekStart.AddDays(5),assignments,absences),Sunday=BuildDayCell(e.Id,WeekStart.AddDays(6),assignments,absences)});BuildStaffing(assignments,db);BuildAlerts(assignments,absences,db);}
 private static string BuildDayCell(int employeeId,DateTime day,List<PlanningAssignment> assignments,List<Absence> absences){var aa=assignments.Where(x=>x.EmployeeId==employeeId&&x.Date.Date==day.Date).OrderBy(x=>x.StartTime).ToList();var absence=absences.FirstOrDefault(x=>x.EmployeeId==employeeId&&x.StartDate.Date<=day.Date&&x.EndDate.Date>=day.Date);var parts=new List<string>();if(absence is not null)parts.Add($"ABW: {absence.Type}");foreach(var item in aa)parts.Add($"{item.Workstation.Name} · {item.Shift?.Name??"Individuell"}\n{item.StartTime:hh\\:mm}–{item.EndTime:hh\\:mm}");return parts.Count==0?"—":string.Join("\n",parts);}
 private void BuildStaffing(List<PlanningAssignment> assignments,AppDbContext db){StaffingRows.Clear();var map=db.Workstations.AsNoTracking().Where(x=>x.IsActive).ToDictionary(x=>x.Id);var groups=assignments.Where(x=>map.ContainsKey(x.WorkstationId)).GroupBy(x=>new{Day=x.Date.Date,x.WorkstationId,x.ShiftId,x.StartTime,x.EndTime}).OrderBy(x=>x.Key.Day).ThenBy(x=>x.Key.StartTime);foreach(var g in groups){var w=map[g.Key.WorkstationId];var f=g.First();var p=g.Select(x=>x.EmployeeId).Distinct().Count();StaffingRows.Add(new WeekStaffingRow{Date=g.Key.Day,DayText=g.Key.Day.ToString("ddd dd.MM.",CultureInfo.GetCultureInfo("de-CH")),WorkstationName=w.Name,ShiftName=f.Shift?.Name??"Individuell",TimeText=$"{g.Key.StartTime:hh\\:mm}–{g.Key.EndTime:hh\\:mm}",PlannedStaff=p,MinimumStaff=w.MinimumStaff,OptimalStaff=w.OptimalStaff,MaximumStaff=w.MaximumStaff,StatusText=p<w.MinimumStaff?"Unterbesetzt":p<w.OptimalStaff?"Knapp besetzt":p>w.MaximumStaff?"Überbesetzt":"OK"});}}
 private void BuildAlerts(List<PlanningAssignment> assignments,List<Absence> absences,AppDbContext db){Alerts.Clear();foreach(var r in StaffingRows){if(r.PlannedStaff<r.MinimumStaff)Alerts.Add(new PlanningAlert{Severity="Rot",Message=$"{r.DayText}: {r.WorkstationName} / {r.ShiftName} unterbesetzt ({r.PlannedStaff}/{r.MinimumStaff})."});else if(r.PlannedStaff>r.MaximumStaff)Alerts.Add(new PlanningAlert{Severity="Gelb",Message=$"{r.DayText}: {r.WorkstationName} / {r.ShiftName} überbesetzt ({r.PlannedStaff}/{r.MaximumStaff})."});}foreach(var a in assignments){var interval=GetInterval(a.Date,a.StartTime,a.EndTime);var absence=absences.FirstOrDefault(x=>x.EmployeeId==a.EmployeeId&&x.StartDate.Date<=interval.End.Date&&x.EndDate.Date>=interval.Start.Date);if(absence is not null)Alerts.Add(new PlanningAlert{Severity="Rot",Message=$"{a.Date:ddd dd.MM.}: {a.Employee.LastName}, {a.Employee.FirstName} ist eingeplant, aber als {absence.Type} abwesend."});var skill=QualificationPlanningService.CheckEmployee(db,a.EmployeeId,a.WorkstationId);if(!skill.IsQualified)Alerts.Add(new PlanningAlert{Severity="Rot",Message=$"{a.Date:ddd dd.MM.}: {a.Employee.LastName}, {a.Employee.FirstName} erfüllt die Pflichtqualifikation für {a.Workstation.Name} nicht. {skill.Message}"});}if(assignments.Count==0)Alerts.Add(new PlanningAlert{Severity="Hinweis",Message="Für diese Woche sind noch keine Einsätze geplant."});}
 private static DateTime GetMonday(DateTime date){var day=(7+((int)date.DayOfWeek-(int)DayOfWeek.Monday))%7;return date.Date.AddDays(-day);}private static(DateTime Start,DateTime End)GetInterval(DateTime date,TimeSpan startTime,TimeSpan endTime){var start=date.Date+startTime;var end=date.Date+endTime;if(end<=start)end=end.AddDays(1);return(start,end);}
}
public class EmployeeWeekRow{public int EmployeeId{get;set;}public string EmployeeName{get;set;}=string.Empty;public string Role{get;set;}=string.Empty;public string Monday{get;set;}=string.Empty;public string Tuesday{get;set;}=string.Empty;public string Wednesday{get;set;}=string.Empty;public string Thursday{get;set;}=string.Empty;public string Friday{get;set;}=string.Empty;public string Saturday{get;set;}=string.Empty;public string Sunday{get;set;}=string.Empty;}
public class WeekStaffingRow{public DateTime Date{get;set;}public string DayText{get;set;}=string.Empty;public string WorkstationName{get;set;}=string.Empty;public string ShiftName{get;set;}=string.Empty;public string TimeText{get;set;}=string.Empty;public int PlannedStaff{get;set;}public int MinimumStaff{get;set;}public int OptimalStaff{get;set;}public int MaximumStaff{get;set;}public string StatusText{get;set;}=string.Empty;}
